blog/user/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import Unauthorized
from flask_login import login_required, current_user
from blog.models import User

users = Blueprint('users', __name__)


@users.route('/')
@login_required
def user_list():
    if current_user.is_staff:
        data = User.query.all()
        return render_template('user/user_list.html', users=data)
    else:
        return user_detail(current_user.id)


@users.route('/<int:pk>')
@login_required
def user_detail(pk: int):
    one_user = None
    if pk == current_user.id or current_user.is_staff:
        one_user = User.query.filter_by(id=pk).one_or_none()
    if one_user is None:
        raise Unauthorized(f"User #{pk} doesn't exist!")
    return render_template('user/user_detail.html', user=one_user)

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>{% block title %}Заголовок{% endblock %}</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" rel="stylesheet">
</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg" style="background-color: #40826d;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src={{ url_for('static', filename='logo.png') }} alt="Logo" width="30" height="24"
            class="d-inline-block align-text-top"> Flask-blog</a>
            <div class="collapse navbar-collapse">
                <div class="navbar-nav">
                    <a class="nav-link {% block article_active %}"{% endblock %} href={{ url_for('articles.list') }}>Статьи</a>
                    <a class="nav-link {% block user_active %}"{% endblock %} href={{ url_for('users.user_list') }}>Пользователи</a>
                    <a class="nav-link {% block author_active %}"{% endblock %} href={{ url_for('authors_app.list') }}>Авторы</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href={{ url_for('auth.logout') }}>Выйти, {{ current_user.username }}</a>
                    {% else %}
                    <a class="nav-link" href={{ url_for('auth.login') }}>Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <p></p>
    {% block body %}

    {% endblock %}

</div>
<script crossorigin="anonymous"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>